services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home 
    networks:
      - net
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_SLAVE_AGENT_PORT=50000
    restart: always
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - net
    environment:
    #  - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    #volumes:
      #- sonarqube_data:/opt/sonarqube/data
      #- sonarqube_extensions:/opt/sonarqube/extensions
      #- sonarqube_logs:/opt/sonarqube/logs
      #- sonarqube_temp:/opt/sonarqube/temp
    restart: always
  mysql-cdy2203:
    container_name: mysql-cdy2203
    build:
      dockerfile: Dockerfile_mysql
    ports:
      - "3306:3306"
    networks:
      - net
networks:
  net:
    driver: bridge